"""Require unique email

Revision ID: 9bf99629aee8
Revises: 8cd17dffabc0
Create Date: 2026-09-29 16:53:09.558106+00:00

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9bf99629aee8"
down_revision: str | Sequence[str] | None = "8cd17dffabc0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f("uq_account_email"), ["email"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_account_email"), type_="unique")

    # ### end Alembic commands ###
