"""Notification, Venue, Event, Ticket, Organization, OrganizationMember

Revision ID: e0a63b0d603e
Revises: c64e003b3587
Create Date: 2026-10-02 01:39:07.082885+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from quickticket.models import PointSerializer
from quickticket.models.money import MoneySerializer

# revision identifiers, used by Alembic.
revision: str = "e0a63b0d603e"
down_revision: str | Sequence[str] | None = "c64e003b3587"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organization",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("organization_id", name=op.f("pk_organization")),
    )
    op.create_table(
        "notification",
        sa.Column("notification_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("email_at", sa.DateTime(), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("content_short", sa.String(length=1024), nullable=False),
        sa.Column("content_full", sa.String(length=4096), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.account_id"],
            name=op.f("fk_notification_account_id_account"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("notification_id", name=op.f("pk_notification")),
    )
    with op.batch_alter_table("notification", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_notification_account_id"), ["account_id"], unique=False
        )

    op.create_table(
        "organization_member",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("acccount_id", sa.Uuid(), nullable=False),
        sa.Column(
            "joined_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("permissions", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["acccount_id"],
            ["account.account_id"],
            name=op.f("fk_organization_member_acccount_id_account"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.organization_id"],
            name=op.f("fk_organization_member_organization_id_organization"),
        ),
        sa.PrimaryKeyConstraint(
            "organization_id", "acccount_id", name=op.f("pk_organization_member")
        ),
    )
    op.create_table(
        "venue",
        sa.Column("venue_id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.String(length=4096), nullable=False),
        sa.Column("theme", sa.String(length=128), nullable=False),
        sa.Column("thumbnail_url", sa.String(length=2000), nullable=False),
        sa.Column("banner_url", sa.String(length=2000), nullable=False),
        sa.Column("location_name", sa.String(length=128), nullable=False),
        sa.Column("location_coords", PointSerializer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.organization_id"],
            name=op.f("fk_venue_organization_id_organization"),
        ),
        sa.PrimaryKeyConstraint("venue_id", name=op.f("pk_venue")),
    )
    with op.batch_alter_table("venue", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_venue_organization_id"), ["organization_id"], unique=False
        )

    op.create_table(
        "event",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("venue_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.String(length=4096), nullable=False),
        sa.Column("theme", sa.String(length=128), nullable=False),
        sa.Column("thumbnail_url", sa.String(length=2000), nullable=False),
        sa.Column("banner_url", sa.String(length=2000), nullable=False),
        sa.Column(
            "starts_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "ends_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("ticket_price", MoneySerializer(), nullable=False),
        sa.Column("max_attendees", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["venue_id"], ["venue.venue_id"], name=op.f("fk_event_venue_id_venue")
        ),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_event")),
    )
    with op.batch_alter_table("event", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_event_venue_id"), ["venue_id"], unique=False)

    op.create_table(
        "ticket",
        sa.Column("ticket_id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("paid_cost", MoneySerializer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.account_id"],
            name=op.f("fk_ticket_account_id_account"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["event.event_id"], name=op.f("fk_ticket_event_id_event")
        ),
        sa.PrimaryKeyConstraint("ticket_id", name=op.f("pk_ticket")),
    )
    with op.batch_alter_table("ticket", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ticket_account_id"), ["account_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_ticket_event_id"), ["event_id"], unique=False)

    with op.batch_alter_table("address", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_address_account_id"), ["account_id"], unique=False)
        batch_op.drop_constraint(batch_op.f("fk_address_account_id_account"), type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_address_account_id_account"),
            "account",
            ["account_id"],
            ["account_id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("address", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_address_account_id_account"), type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_address_account_id_account"), "account", ["account_id"], ["account_id"]
        )
        batch_op.drop_index(batch_op.f("ix_address_account_id"))

    with op.batch_alter_table("ticket", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ticket_event_id"))
        batch_op.drop_index(batch_op.f("ix_ticket_account_id"))

    op.drop_table("ticket")
    with op.batch_alter_table("event", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_event_venue_id"))

    op.drop_table("event")
    with op.batch_alter_table("venue", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_venue_organization_id"))

    op.drop_table("venue")
    op.drop_table("organization_member")
    with op.batch_alter_table("notification", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notification_account_id"))

    op.drop_table("notification")
    op.drop_table("organization")
    # ### end Alembic commands ###
