"""Allow all cascades (dangerous!)

Revision ID: 0d37fa1087da
Revises: 5904f5d47408
Create Date: 2026-10-05 15:02:35.343889+00:00

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0d37fa1087da"
down_revision: str | Sequence[str] | None = "5904f5d47408"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("organization_member", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_organization_member_acccount_id_account"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_organization_member_acccount_id_account"),
            "account",
            ["acccount_id"],
            ["account_id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("ticket", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_ticket_event_id_event"), type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_ticket_event_id_event"),
            "event",
            ["event_id"],
            ["event_id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("venue", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_venue_organization_id_organization"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_venue_organization_id_organization"),
            "organization",
            ["organization_id"],
            ["organization_id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("venue", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_venue_organization_id_organization"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_venue_organization_id_organization"),
            "organization",
            ["organization_id"],
            ["organization_id"],
        )

    with op.batch_alter_table("ticket", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_ticket_event_id_event"), type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_ticket_event_id_event"), "event", ["event_id"], ["event_id"]
        )

    with op.batch_alter_table("organization_member", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_organization_member_acccount_id_account"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_organization_member_acccount_id_account"),
            "account",
            ["acccount_id"],
            ["account_id"],
        )

    # ### end Alembic commands ###
