"""Add missing index on venue.venue_id

Revision ID: d8f0a832401c
Revises: 6f01e38de460
Create Date: 2026-10-06 23:59:42.773665+00:00

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d8f0a832401c"
down_revision: str | Sequence[str] | None = "6f01e38de460"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_account_created_at"), ["created_at"], unique=False)

    with op.batch_alter_table("event", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_event_created_at"), ["created_at"], unique=False)

    with op.batch_alter_table("organization", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_organization_created_at"), ["created_at"], unique=False
        )

    with op.batch_alter_table("ticket", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ticket_created_at"), ["created_at"], unique=False)

    with op.batch_alter_table("venue", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_venue_created_at"), ["created_at"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("venue", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_venue_created_at"))

    with op.batch_alter_table("ticket", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ticket_created_at"))

    with op.batch_alter_table("organization", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_organization_created_at"))

    with op.batch_alter_table("event", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_event_created_at"))

    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_account_created_at"))

    # ### end Alembic commands ###
