"""Add account.openid_sub

Revision ID: c64e003b3587
Revises: 9bf99629aee8
Create Date: 2026-09-30 12:38:52.807300+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c64e003b3587"
down_revision: str | Sequence[str] | None = "9bf99629aee8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.add_column(sa.Column("openid_sub", sa.String(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f("uq_account_openid_sub"), ["openid_sub"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_account_openid_sub"), type_="unique")
        batch_op.drop_column("openid_sub")

    # ### end Alembic commands ###
