"""Add account_openid table

Revision ID: 5904f5d47408
Revises: 1e74e162c5ca
Create Date: 2026-10-03 00:36:54.410199+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5904f5d47408"
down_revision: str | Sequence[str] | None = "1e74e162c5ca"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_openid",
        sa.Column("issuer", sa.String(length=2000), nullable=False),
        sa.Column("sub", sa.String(length=2000), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("id_token", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.account_id"],
            name=op.f("fk_account_openid_account_id_account"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("issuer", "sub", name=op.f("pk_account_openid")),
    )
    with op.batch_alter_table("account_openid", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_account_openid_account_id"), ["account_id"], unique=False
        )

    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_account_openid_sub"), type_="unique")
        batch_op.drop_column("openid_sub")

    with op.batch_alter_table("event", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_event_venue_id"), ["venue_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("event", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_event_venue_id"))

    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.add_column(sa.Column("openid_sub", sa.VARCHAR(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f("uq_account_openid_sub"), ["openid_sub"])

    with op.batch_alter_table("account_openid", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_account_openid_account_id"))

    op.drop_table("account_openid")
    # ### end Alembic commands ###
