services:
  backend:
    build: .
    ports:
      - 8000:8000
    env_file: .env
    environment:
      # BACKEND__ROOT_PATH: '/backend'
      BACKEND__CACHE__URL: 'redis://default:abc123@cache:6379'  # 'sqlite:///data/quickticket-cache.db'
      BACKEND__DB__URL: 'postgresql+psycopg://quickticket:abc123@db:5432/quickticket?sslmode=prefer'  # 'sqlite+aiosqlite:///data/quickticket.db'
      # BACKEND__FRONTEND__BUILTIN: '0'
      # BACKEND__FRONTEND__DEFAULT_REDIRECT_URI: 'http://127.0.0.1:5173/'
      # BACKEND__FRONTEND__REDIRECT_URIS: '["http://127.0.0.1:5173/*", "http://localhost:5173/*"]'
      # BACKEND__LOG__DEBUG: '0'
      # BACKEND__LOG__PROFILING: '0'
      # BACKEND__LOG__VERBOSITY: '1'
      # BACKEND__OPENAPI__URL: ''  # '/openapi.json'
      # BACKEND__OPENAPI__SWAGGER_URL: ''  # '/docs'
      # BACKEND__OPENAPI__REDOC_URL: ''  # '/redoc'
      # # The client ID, secret, and discovery URL are required for authentication
      # BACKEND__OPENID__CLIENT_ID: 'abc123'
      # BACKEND__OPENID__CLIENT_SECRET: 'abc123'
      # BACKEND__OPENID__DISCOVERY_URL: 'https://example.com/.well-known/openid-configuration'
      # # Admin group is optional if your provider adds a "groups" claim in its ID tokens
      # BACKEND__OPENID__ADMIN_GROUP: 'admins'
      # BACKEND__SECURITY__ALLOWED_HOSTS: '["127.0.0.1", "localhost"]'
      # BACKEND__SECURITY__TRUSTED_PROXIES: '["127.0.0.1"]'
      # BACKEND__SECURITY__CSRF_SECRET: 'insecure_qt9u0SCF3DuSJ69ZrqvzlJGTWxx7C5wh'
      # BACKEND__SECURITY__COOKIE_ENCRYPTION_SECRETS: '["Qfw1bmzNtFba8qLxYZzxtEDfgd4P58LCDKiuMezO6lU="]'
      # BACKEND__SECURITY__TOKEN_LEEWAY: '30'
      # BACKEND__SMTP__HOST: 'example.com'
      # BACKEND__SMTP__PORT: '465'
      # BACKEND__SMTP__TLS: 'implicit'
      # BACKEND__SMTP__USERNAME: 'user@example.com'
      # BACKEND__SMTP__PASSWORD: 'abc123'
      # BACKEND__SMTP__FROM_EMAIL: 'User Name <user@example.com>'
      FORCE_COLOR: '1'
    restart: always
    volumes:
      # Use this volume if either the cache or database are backed by SQLite.
      - backend-data:/app/data
    depends_on:
      cache:
        condition: service_healthy
      db:
        condition: service_healthy
    pre_start:
      - command: ['alembic', 'upgrade', 'head']  # run migrations on startup
    develop:
      watch:
        - action: sync+restart
          path: ./src
          target: /app/src
          initial_sync: true
        - action: rebuild
          path: pyproject.toml
        - action: rebuild
          path: uv.lock

  cache:
    # https://hub.docker.com/_/redis/
    image: docker.io/library/redis:8-alpine
    command:
      - 'redis-server'
      - '--appendonly'
      - 'yes'
      - '--loglevel'
      - 'warning'
      - '--requirepass'
      - '${REDIS_PASSWORD:-abc123}'
    ports:
      - 127.0.0.1:6379:6379
    environment:
      REDIS_ARGS: 'abc123'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 1s
      timeout: 5s
      retries: 10
    restart: always
    volumes:
      - cache-data:/data

  db:
    # https://hub.docker.com/_/postgres/
    image: docker.io/library/postgres:18-alpine
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_USER: 'quickticket'
      POSTGRES_DB: 'quickticket'
      POSTGRES_PASSWORD: 'abc123'
      POSTGRES_INITDB_ARGS: '--encoding=UTF8 --lc-collate=en_US.UTF-8 --lc-ctype=en_US.UTF-8'
      # Healthcheck
      PGUSER: 'quickticket'
      PGDATABASE: 'quickticket'
      PGPASSWORD: 'abc123'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 1s
      timeout: 5s
      retries: 10
    restart: always
    volumes:
      - db-data:/var/lib/postgresql
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf:ro

  # TODO: add S3 (https://hub.docker.com/r/dxflrs/garage)

volumes:
  backend-data:
  cache-data:
  db-data:
