[build-system]
requires = ["uv_build~=0.12.17"]
build-backend = "uv_build"

[project]
name = "quickticket"
version = "0.1.0"
readme = "README.md"
authors = [
    { name = "thegamecracks", email = "61257169+thegamecracks@users.noreply.github.com" },
    { name = "Ashley Scott", email = "lunarmeadow@protonmail.com" },
]
requires-python = ">=3.14"
dependencies = [
    "aiosqlite>=0.22.1",
    "alembic>=1.20.0",
    "authlib>=1.8.0",
    "fastapi[standard]>=0.141.1",
    "httpx2>=2.13.1",
    "joserfc>=1.7.5",
    "obstore>=0.11.1",
    "pillow>=12.3.0",
    "psycopg[binary]>=3.3.6",
    "pydantic>=2.13.5",
    "pydantic-extra-types>=2.11.1",
    "pydantic-settings>=2.15.0",
    "redis[hiredis]>=8.1.0",
    "sqlalchemy[asyncio]>=2.1.1",
    "uvicorn>=0.54.0",
    "whenever>=0.10.5",
]

[project.scripts]
quickticket = "quickticket.manage:main"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "ruff>=0.16.9",
]

[tool.fastapi]
entrypoint = "quickticket.app:app"

# https://docs.pytest.org/en/stable/reference/reference.html#ini-options-ref
# https://pytest-django.readthedocs.io/en/latest/configuring_django.html
[tool.pytest]
DJANGO_SETTINGS_MODULE = "quickticket.settings"
