[build-system]
requires = ["uv_build~=0.12.17"]
build-backend = "uv_build"

[project]
name = "quickticket"
version = "0.1.0"
readme = "README.md"
authors = [
    { name = "thegamecracks", email = "61257169+thegamecracks@users.noreply.github.com" },
    { name = "Ashley Scott", email = "lunarmeadow@protonmail.com" },
]
requires-python = ">=3.14"
dependencies = [
    "django>=6.1.1",
    "django-pyoidc>=1.0.13",
    "djangorestframework>=3.18.1",
    "obstore>=0.11.1",
    "pillow>=12.3.0",
    "psycopg[binary]>=3.3.6",
    "pytest-django>=4.14.0",
    "redis[hiredis]>=8.1.0",
    "whenever>=0.10.5",
]

[project.scripts]
quickticket = "quickticket.manage:main"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

# https://docs.pytest.org/en/stable/reference/reference.html#ini-options-ref
# https://pytest-django.readthedocs.io/en/latest/configuring_django.html
[tool.pytest]
DJANGO_SETTINGS_MODULE = "quickticket.settings"
